---
Name: goldfinch-sitemap
After:
  - '#googlesitemaproutes'
---
SilverStripe\Control\Director:
  rules:
    'sitemap.xml': 'Goldfinch\Sitemap\Controllers\GoogleSitemapController'

Wilr\GoogleSitemaps\Control\GoogleSitemapController:
  extensions:
    - Goldfinch\Sitemap\Extensions\SitemapControllerExtension

Wilr\GoogleSitemaps\GoogleSitemap:
  enabled: true
  objects_per_sitemap: 1000
  google_notification_enabled: false
  use_show_in_search: true
